apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # Backend Image Path
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_7872c424aa48